import localFont from "next/font/local";
import "./globals.css";
import { Outfit } from "next/font/google";
import Provider from "./provider";
// import { ClerkProvider } from "@clerk/nextjs";
import dynamic from "next/dynamic";
import ClerkProviderWrapper from "@/components/ClerkProviderWrapper";
import { Toaster } from "@/components/ui/sonner";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({
  subsets: ["latin"],
});

// Dynamically import ClerkProvider to prevent SSR mismatch
// const ClerkProvider = dynamic(() => import("@clerk/nextjs").then(mod => mod.ClerkProvider), { ssr: false });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <ClerkProviderWrapper>
          <Provider>{children}</Provider>
          <Toaster />
        </ClerkProviderWrapper>
      </body>
    </html>
  );
}
